name: 🟢 Daily Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update dummy file
        run: |
          echo "Last update: $(date)" > .keepalive

      - name: Commit and Push
        run: |
          git config user.name "duytrancoder"
          git config user.email "trankhanhduy0103.as@gmail.com"
          
          git add .keepalive
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: daily auto commit [skip ci]"
            git push origin HEAD:main
          fi
